// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/entreprise-besoin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entreprise-besoin">> = Specific
  const handler = {} as typeof import("../../../src/app/entreprise-besoin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/bts-cg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/bts-cg">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/bts-cg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/bts-gpme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/bts-gpme">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/bts-gpme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/bts-mco/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/bts-mco">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/bts-mco/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/bts-mos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/bts-mos">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/bts-mos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/bts-ndrc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/bts-ndrc">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/bts-ndrc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/formations/tp-advf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formations/tp-advf">> = Specific
  const handler = {} as typeof import("../../../src/app/formations/tp-advf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentions-legales">> = Specific
  const handler = {} as typeof import("../../../src/app/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orientation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orientation">> = Specific
  const handler = {} as typeof import("../../../src/app/orientation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
